CoV.Web/CoV.Web/Models/ErrorViewModel.cs
using System;

namespace CoV.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoV.Web/CoV.Web/Controllers/AdminController.cs
using System.Reflection.Metadata;
using System.Security.Claims;
using System.Security.Principal;
using CoV.Common.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoV.Web.Controllers
{

    /// <summary>
    /// Admin Controler 
    /// </summary>
    [Authorize]
    public class AdminController : Controller
    {
        /// <summary>
        /// show 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return
            View("Index");
        }
    }
}

CoV.Web/CoV.Web/Controllers/CartController.cs
using System.Collections.Generic;
using AutoMapper;
using CoV.Service.DataModel;
using CoV.Service.Service;
using CoV.Web.Infrastructure.Helper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CoV.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;

        public CartController(IProductService productService, IMapper mapper)
        {
            _productService = productService;
            _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var sessionEmail = HttpContext.Session.GetString("SessionEmail");
            var cart = SessionHelper.GetObjectFromJson<List<CartViewModel>>(HttpContext.Session, "cart");
            var cartCustomer = cart.FindAll(x => x.Name == sessionEmail);
            ViewBag.cart = cartCustomer;
            return View();
        }
        
        [HttpGet]
        public IActionResult Buy(int id)
        {
            var sessionEmail = HttpContext.Session.GetString("SessionEmail");
            if (sessionEmail == null)
            {
                return Redirect("/Customer/CreateAndUpdate");
            }
            else
            {
                var product = _productService.GetByIdCart(id);
                if (SessionHelper.GetObjectFromJson<List<CartViewModel>>(HttpContext.Session, "cart") == null)
                {
                    List<CartViewModel> cart = new List<CartViewModel>();
                
                    cart.Add(new CartViewModel {Product =  product,Name = sessionEmail  ,ProductId = id, Quantity = 1 });
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                }
                else
                {
                    List<CartViewModel> cart = SessionHelper.GetObjectFromJson<List<CartViewModel>>(HttpContext.Session, "cart");
                    int index = IsExist(id);
                    if (index != -1)
                    {
                        cart[index].Quantity++;
                    }
                    else
                    {
                        cart.Add(new CartViewModel {Product =  product,Name = sessionEmail  ,ProductId = id, Quantity = 1 });
                    }
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                }
                return Redirect("/home/home");
            }
        }
        
        
       [HttpGet]
        public IActionResult Remove(int id)
        {
            var cart = SessionHelper.GetObjectFromJson<List<CartViewModel>>(HttpContext.Session, "cart");
            int index = IsExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

        private int IsExist(int id)
        {
            var sessionEmail = HttpContext.Session.GetString("SessionEmail");
            List<CartViewModel> cart = SessionHelper.GetObjectFromJson<List<CartViewModel>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id) && cart[i].Name.Equals(sessionEmail) )
                {
                    return i;
                }
            }
            return -1;
        }

        [HttpGet]
        public IActionResult EditQuantity( int id, int quantity)
        {
            List<CartViewModel> cart = SessionHelper.GetObjectFromJson<List<CartViewModel>>(HttpContext.Session, "cart");
            var product = _productService.GetByIdCart(id);
            if (quantity <= 0)
            {
                return new JsonResult(cart);
            }
            int index = IsExist(id);
            if (index != -1)
            {
                cart[index].Quantity = quantity + 1;
            }
            else
            {
                cart.Add(new CartViewModel {Product =  product, ProductId = id, Quantity = 1 });

            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return new JsonResult(cart);
        }
        
        [HttpGet]
        public IActionResult EditQuantityDown( int id, int quantity)
        {
            List<CartViewModel> cart = SessionHelper.GetObjectFromJson<List<CartViewModel>>(HttpContext.Session, "cart");
            var product = _productService.GetByIdCart(id);
            int index = IsExist(id);
            if (quantity <= 0)
            {
                return new JsonResult(cart);
            }
            if (index != -1)
            {
                cart[index].Quantity = quantity - 1;
            }
            else
            {
                cart.Add(new CartViewModel {Product =  product, ProductId = id, Quantity = 1 });

            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return new JsonResult(cart);
        }
        
        [HttpGet]
        public IActionResult EditQuantityMouseleave( int id, int quantity)
        {
            List<CartViewModel> cart = SessionHelper.GetObjectFromJson<List<CartViewModel>>(HttpContext.Session, "cart");
            var product = _productService.GetByIdCart(id);
            int index = IsExist(id);
            if (quantity <= 0)
            {
                return new JsonResult(cart);
            }
            if (index != -1)
            {
                cart[index].Quantity = quantity;
            }
            else
            {
                cart.Add(new CartViewModel {Product =  product, ProductId = id, Quantity = 1 });

            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return new JsonResult(cart);
        }
    }
    
}

CoV.Web/CoV.Web/Controllers/CustomerController.cs
using System;
using CoV.Common.Resources;
using CoV.Service.DataModel;
using CoV.Service.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CoV.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;
        public CustomerController(ICustomerService customerService  )
        {
            _customerService = customerService;
        }
        
        // GET
        [HttpGet]
        public IActionResult GetAll()
        {
            var Customer = _customerService.GetAll();
            return
            View(Customer);
        }

        /// <summary>
        /// Delete A customer
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult delete(int id)
        {
            _customerService.Delete(id);
            return RedirectToAction("GetAll");
        }
        
        [HttpGet]
        public IActionResult CreateAndUpdate()
        {
                return View();
        }
        
        /// <summary>
        ///  Create Or Update a Customer
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult CreateAndUpdate(CustomerViewModel model)
        {
            var sessionEmail = HttpContext.Session.GetString("SessionEmail");
            if (sessionEmail != null)
            {
                return Redirect("/home/home");
            }
            if (model.PassWord != model.ConfiguePassWord)
            {
                ModelState.AddModelError(string.Empty, MessageResource.ConfiguePassword);
                return View();
            }
            if (_customerService.CheckAccountCustomer(model) == true) //tai khoan da ton tai
            {
                ModelState.AddModelError(String.Empty, MessageResource.LoginCustomerSingUpFailed);
                return View();
            }
            _customerService.CreateOrUpdate(model);
            return Redirect("/home/home");
        }
    
        [HttpGet]
        public IActionResult LoginCustomer()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LoginCustomer( loginCustomerViewModel model)
        {
            if (_customerService.CheckLoginAccountCustomer(model) == false) //tai khoan chua ton tai
            {
                ModelState.AddModelError(String.Empty, MessageResource.CustomerSingUpFailed);
                return View();
            }

            if (_customerService.CheckPass(model) == true)
            {
                var customerName = _customerService.GetByName(model.Email);
                HttpContext.Session.SetString("SessionName",customerName.LastName);
                HttpContext.Session.SetString("SessionEmail",customerName.Email);
                HttpContext.Session.SetString("SessionPhone",customerName.PhoneNumber);
                return Redirect("/home/home");
            }
            else
            {
                ModelState.AddModelError(String.Empty, MessageResource.UserLoginFailed);
            }
            return View();
        }
        
        /// <summary>
        /// Logout Customer remove Session
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult  Logout()
        {    
            HttpContext.Session.Remove("SessionEmail");
            HttpContext.Session.Remove("SessionName");
            HttpContext.Session.Remove("SessionPhone");
            return  Redirect("/Customer/LoginCustomer");
        }
    }
}

CoV.Web/CoV.Web/Controllers/ErrorController.cs
using System;
using CoV.Common.Resources;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace CoV.Web.Controllers
{
    public class ErrorController : Controller
    {
        
        
        /// <summary>
        ///  error 404
        /// </summary>
        /// <returns>view</returns>
        [HttpGet]
        public IActionResult pagenotfound()
        {
            try
            {
                Log.Error(MessageResource.errer404);
                return
                 View();
            }
            catch (Exception e)
            {
                Log.Error(MessageResource.errer404 + e);
                throw;
            }
            return
            View();
        }
        
        /// <summary>
        /// eror 500
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult systemerror()
        {
            try
            {
                Log.Error(MessageResource.error500);
                return
                    View();
            }
            catch (Exception e)
            {
                
                Log.Error(MessageResource.error500 + e  );
                throw;
            }
        }
    
        /// <summary>
        /// Error Assessdenief
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult accessdenied()
        {
            try
            {
                Log.Error(MessageResource.error401);
                return View();
            }
            catch (Exception e)
            {
                Log.Error(MessageResource.error401 + e);
                throw;
            }
        }

 
    }
}

CoV.Web/CoV.Web/Views/Shared/FilterExpired.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Error";
}
    <div class="vc-container">
        <div class="vc-content">
            <h3 class="vc-heading">Request ExpiredDate</h3>
            <h3><p class="vc-sub-heading">Go to <a style="text-decoration: none" asp-action="Index" asp-controller="Admin"><span class="blink-infinite">Home</span></a></p></h3>
            <p class="vc-sub-heading">OR <a style="text-decoration: none; color: red" asp-action="ExpiredDate" asp-controller="Account"><span class="blink-infinite">Extendible</span></a></p>
        </div>
    </div>
    
    

CoV.Web/CoV.Web/Views/Shared/_Error.cshtml
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Error !!!</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/error404/css500/style.css">

</head>
<body>
<div class="container-fluid">
    @RenderBody()
</div>
</body>

CoV.Web/CoV.Web/Views/Shared/_FrontEndLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
	<title>Trang Chủ</title>
    <link rel="stylesheet" href="~/Frontend/css/template.css">
    <link rel="stylesheet" href="~/Frontend/css/style.css">
    <link rel="stylesheet" href="~/Frontend/css/owl.css">
    <link rel="stylesheet" href="~/Frontend/css/font-icon.css">
    <link rel="stylesheet" href="~/Frontend/css/font-arsenal.css">
	<link rel="stylesheet" href="~/Frontend/css/animate.css">
	
	<link rel="stylesheet" href="~/Frontend/css/dialog_modal.css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<body>
<header>
	<div class="container p-0">
		<div class="row align-items-center">

			<div class="col-md-8">
				<ul class="">
					<li>
						<a  asp-controller="Home"  asp-action="About" >
							Giới thiệu
						</a>
					</li>
					<li>
						<a asp-action="Contact"  asp-controller="Home">
							Liên hệ
						</a>
					</li>
					<li>
						<a href="#">
							Tin tức sự kiện
						</a>
					</li>
							
				</ul>
			</div>
			<div class="col-md-4">
				<ul class="justify-content-end">
					<li id="login_Customer">
						<a asp-controller="Customer" asp-action="LoginCustomer">
							<i class="fas fa-sign-in-alt"></i>
							Đăng nhập 
						</a>
					</li>
					<li id="Create_Customer" >
						<a asp-controller="Customer" asp-action="CreateAndUpdate">
							<i class="fas fa-sign-out-alt"></i>
							Đăng ký
						</a>
					</li>
					<li id="logout-Customer" >
						<a asp-controller="Customer" asp-action="Logout">
							<i class="fas fa-sign-out-alt"></i>
							Đăng xuất
						</a>
					</li>
					<li  id="icon-customer">
						<a asp-controller="" asp-action="">
							<i class="fas fa-user-cog"></i>
							@Context.Session.GetString("SessionName")
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</header>
<nav class="main_menu" id="main_menu">
			<div class="container p-0">
				<div class="row align-items-center">
					<div class="col-md-2">
						<div class="logo">
							<a asp-controller="Home" asp-action="Home">
								<img src="~/Frontend/images/my-logo.png" alt="">
							</a>
						</div>
					</div>
					<div class="col-md-8">
						<ul class="ul_main">
							<li class="active">
								<a  asp-controller="Home" asp-action="Home">
									TRANG CHỦ
								</a>
							</li>
							<li>
								<a asp-controller="Home" asp-action="Blog">
									GIÀY NAM 
								</a>
								<ul class="ul_sub">
									<li>
										<a href="blog.html">Giày Cao Cổ</a>
									</li>
									<li>
										<a href="blog.html">Giày da</a>
									</li>
									<li>
										<a href="blog.html">Giày thể thao</a>
									</li>
								</ul>
								
							</li>
							<li>
								<a href="product.html">
									GIÀY NỮ
								</a>
								<ul class="ul_sub">
									<li>
										<a href="product.html">Giày cao cổ</a>
									</li>
									<li>
										<a href="product.html">Giày công sở</a>
									</li>
								</ul>
								
							</li>
							<li>
								<a href="product.html">
									GIÀY TRẺ EM 
								</a>
								<ul class="ul_sub">
									<li>
										<a href="product.html">Đáng yêu</a>
									</li>
									<li>
										<a href="product.html">Phong cách</a>
									</li>
								</ul>
								
							</li>
							<li>
								<a href="#">
									GIÀY THỂ THAO 
								</a>
							</li>
							<li>
								<a href="#">
									GIÀY CÔNG SỞ
								</a>
							</li>
							<li class="control_search">
								<a href="javascript:void(0)">
									<i class="fas fa-search"></i>
								</a>
							</li>
						</ul>
					</div>

					<div class="col-md-2">
						<ul class="ul_main justify-content-end">
							<li>
								<a href="#">
									<i class="far fa-heart"></i>
								</a>
							</li>
							<li>
								<a  asp-controller="Cart" asp-action="Index">
									<i class="fas fa-shopping-cart"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="search">
					<div class="row justify-content-center">
						<div class="col-md-12">
							<form action="#" class="form-search">
								<div class="form-group">
									<input class="form-control" type="text" placeholder="Tìm kiếm" />
									<button class="btn-search" type="submit">
										<i class="fas fa-search"></i>
									</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</nav>
		
		<nav class="main_menu" id="fixed_menu">
			<div class="container p-0">
				<div class="row align-items-center">
					<div class="col-md-2">
						<div class="logo">
							<a href="index.html">
								<img src="~/Frontend/images/my-logo.png" alt="">
							</a>
						</div>
					</div>
					<div class="col-md-8">
						<ul class="ul_main">
							<li class="active">
								<a href="index.html">
									Trang Chủ
								</a>
							</li>
							<li>
								<a href="#">
									Nam
								</a>
							</li>
							<li>
								<a href="blog.html">
									Nữ
								</a>
								<ul class="ul_sub">
									<li>
										<a href="blog.html">Tin nhà đất</a>
									</li>
									<li>
										<a href="blog.html">Tin nhà đất</a>
									</li>
									<li>
										<a href="blog.html">Tin nhà đất</a>
									</li>
								</ul>
								
							</li>
							<li>
								<a href="product.html">
									Bé trai
								</a>
								<ul class="ul_sub">
									<li>
										<a href="product.html">Nấm con cua</a>
									</li>
									<li>
										<a href="product.html">Nấm con bò</a>
									</li>
								</ul>
								
							</li>
							<li>
								<a href="#">
									Bé gái
								</a>
							</li>
							<li>
								<a href="#">
									Công sở
								</a>
							</li>
							<li>
								<a href="#">
									Thể thao
								</a>
							</li>
							<li class="control_search">
								<a href="javascript:void(0)">
									<i class="fas fa-search"></i>
								</a>
							</li>
						</ul>
					</div>

					<div class="col-md-2">
						<ul class="ul_main justify-content-end">
							<li>
								<a href="#">
									<i class="far fa-heart"></i>
								</a>
							</li>
							<li>
								<a href="#">
									<i class="fas fa-shopping-cart"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="search">
					<div class="row justify-content-center">
						<div class="col-md-12">
							<form action="#" class="form-search">
								<div class="form-group">
									<input class="form-control" type="text" placeholder="Tìm kiếm" />
									<button class="btn-search" type="submit">
										<i class="fas fa-search"></i>
									</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</nav>
		
		<section class="banner-top">
			<div class="owl-carousel owl-theme" id="main_slide">
				<div class="item">
					<div class="banner">
						<div class="img-banner">
							<img src="~/Frontend/images/banner-top-01.jpg" alt="">
						</div>
					</div>
				</div>
				<div class="item">
					<div class="banner">
						<div class="img-banner">
							<img src="~/Frontend/images/banner-top-02.jpg" alt="">
						</div>
					</div>
				</div>
				<div class="item">
					<div class="banner">
						<div class="img-banner">
							<img src="~/Images/banner-6.jpg" alt="">
						</div>
					</div>
				</div>
				<div class="item">
					<div class="banner">
						<div class="img-banner">
							<img src="~/Images/banner-5.jpg" alt="">
						</div>
					</div>
				</div>

			</div>
		</section>

		
@RenderBody()

<footer class="footer">
<div class="container p-0">
<div class="top-footer">
	<div class="row">
		<div class="col-md-3">
			<h3 class="title">
				Trợ giúp
			</h3>	
			<div class="list-link">
				<ul>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Trạng thái đơn hàng
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Hình thức giao hàng
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Hình thức thanh toán
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Chính sách đổi trả
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Chính sách bảo hành
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Chính sách khách hàng thân thiết
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="col-md-3">
			<h3 class="title">
				Thông tin
			</h3>
			<div class="list-link">
				<ul>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Tuyển Dụng
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Hệ thống cửa hàng
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Liên hệ hợp tác
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Q&A
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="col-md-3">
			<h3 class="title">
				Về chúng tôi
			</h3>
			<div class="list-link">
				<ul>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Về Bitis
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Câu chuyện Biti's
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Bước tiến phát triển
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Hoạt Động
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-chevron-right"></i>
							Liên hệ
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="col-md-3">
			<h3 class="title">
				Liên hệ với chúng tôi
			</h3>
			<div class="list-contact">
				<ul>
					<li>
						<div class="icon">
							<i class="fas fa-map-marker-alt"></i>
						</div>
						<div class="text">
							<h4 class="title-text">
								ADDRESS
							</h4>
							<div class="dt-txt">
								Minh Khai - Bắc Từ Liêm - Hà Nội
							</div>
						</div>
					</li>

					<li>
						<div class="icon">
							<i class="fas fa-mobile"></i>
						</div>
						<div class="text">
							<h4 class="title-text">
								PHONE
							</h4>
							<div class="dt-txt">
								0965319086 (24/7 Support Line)
							</div>
						</div>
					</li>

					<li>
						<div class="icon">
							<i class="fas fa-fax"></i>
						</div>
						<div class="text">
							<h4 class="title-text">
								FAX
							</h4>
							<div class="dt-txt">
								(123) 123-4567
							</div>
						</div>
					</li>

					<li>
						<div class="icon">
							<i class="fas fa-envelope"></i>
						</div>
						<div class="text">
							<h4 class="title-text">
								EMAIL
							</h4>
							<div class="dt-txt">
								Chuonghvc2901@gmail.com
							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class="bot-footer">
	<div class="row align-items-center justify-content-center">
		<div class="col-md-4">
			<ul class="list-ft">
				<li>
					<a href="#">
						Điều khoản
					</a>
				</li>
				<li>
					<a href="#">
						Chính sách bảo mật
					</a>
				</li>
				<li>
					<a href="#">
						Hướng dẫn sử dụng
					</a>
				</li>
			</ul>
		</div>
		<div class="col-md-4">
			<div class="img-ddk">
				<img src="~/Frontend/images/Da-dang-ky-bo-cong-thuong.png" alt="">
			</div>
		</div>
		<div class="col-md-4">
			<div>
				Giấy CNĐKDN: 0301340497 được cấp ngày 20/01/1992,
				được sửa đổi lần thứ 20 ngày 28/12/2015 bởi Sở Kế hoạch và Đầu tư TPHCM
			</div>
		</div>
	</div>
</div>
</div>
</footer>
<button class="back-to-top">
	<i class="fas fa-chevron-up"></i>
</button>

<button id="btn_to_form_book">
	<i class="fas fa-share"></i>
</button>


<script src="~/Frontend/js/jquery.js"></script>
<script src="~/Frontend/js/owl.js"></script>
<script src="~/Frontend/js/app.js"></script>
<script src="~/Frontend/js/wow.js"></script>
<script>
    new WOW().init();
</script>
@RenderSection("Scripts", required: false)
<script>
    // login logout customer
    var SessionEmail = '@HttpContextAccessor.HttpContext.Session.GetString("SessionName")';
    if (SessionEmail == "") {
        $("#icon-customer").attr("hidden", "");
	    $("#logout-Customer").attr("hidden", "");

    } else {
        $("#Create_Customer").attr("hidden", "");
        $("#login_Customer").attr("hidden", "");
        $("#icon-customer").show();
    }
    
    
</script>
</body>

</html>

CoV.Web/CoV.Web/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
@RenderBody()
<!-- /.login-box -->

<!-- jQuery -->
<script src="~plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="~dist/js/adminlte.min.js"></script>

</body>
</html>

CoV.Web/CoV.Web/Views/Shared/_SlideBar.cshtml
<!-- jQuery -->
<script src="plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="plugins/moment/moment.min.js"></script>
<script src="plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="dist/js/demo.js"></script>